project:
  type: website

website:
  title: "website"
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: rome-periodization.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



